name: holoviz_2021
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.6
  - xarray==0.16.2
  - metpy==1.0
  - pandas==1.2.2
  - numpy==1.19.5
  - netcdf4==1.5.3
  - jupyterlab
  - cartopy==0.19.0
  - matplotlib==3.3.3
  - mamba
  - pydap==3.2.2
  - dask==2021.2.0
  - datashader==0.12.0
  - geoviews==1.8.2
  - holoviews==1.14.1
  - bokeh==2.2.3
  - contextily==1.0.1
